/*
 * Paperless Rest Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PaperLessApi.Converters;

namespace PaperLessApi.DTOs
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GetDocumentSuggestions200Response 
    {
        /// <summary>
        /// Gets or Sets Correspondents
        /// </summary>
        [Required]
        [DataMember(Name="correspondents", EmitDefaultValue=false)]
        public List<Object> Correspondents { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [Required]
        [DataMember(Name="tags", EmitDefaultValue=false)]
        public List<Object> Tags { get; set; }

        /// <summary>
        /// Gets or Sets DocumentTypes
        /// </summary>
        [Required]
        [DataMember(Name="document_types", EmitDefaultValue=false)]
        public List<Object> DocumentTypes { get; set; }

        /// <summary>
        /// Gets or Sets StoragePaths
        /// </summary>
        [Required]
        [DataMember(Name="storage_paths", EmitDefaultValue=false)]
        public List<Object> StoragePaths { get; set; }

        /// <summary>
        /// Gets or Sets Dates
        /// </summary>
        [Required]
        [DataMember(Name="dates", EmitDefaultValue=false)]
        public List<Object> Dates { get; set; }

    }
}
