/*
 * Paperless Rest Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PaperLessApi.Converters;

namespace PaperLessApi.DTOs
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GetTasks200ResponseInner 
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=true)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets TaskId
        /// </summary>
        [Required]
        [DataMember(Name="task_id", EmitDefaultValue=false)]
        public string TaskId { get; set; }

        /// <summary>
        /// Gets or Sets TaskFileName
        /// </summary>
        [Required]
        [DataMember(Name="task_file_name", EmitDefaultValue=false)]
        public string TaskFileName { get; set; }

        /// <summary>
        /// Gets or Sets DateCreated
        /// </summary>
        [Required]
        [DataMember(Name="date_created", EmitDefaultValue=false)]
        public string DateCreated { get; set; }

        /// <summary>
        /// Gets or Sets DateDone
        /// </summary>
        [DataMember(Name="date_done", EmitDefaultValue=false)]
        public string DateDone { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [Required]
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [Required]
        [DataMember(Name="result", EmitDefaultValue=false)]
        public string Result { get; set; }

        /// <summary>
        /// Gets or Sets Acknowledged
        /// </summary>
        [Required]
        [DataMember(Name="acknowledged", EmitDefaultValue=true)]
        public bool Acknowledged { get; set; }

        /// <summary>
        /// Gets or Sets RelatedDocument
        /// </summary>
        [DataMember(Name="related_document", EmitDefaultValue=false)]
        public string RelatedDocument { get; set; }

    }
}
