version: '3.4'

services:
  paperlessapi:
    image: paperless-api
    container_name: paperless-api
    build:
      context: .
      dockerfile: ./src/PaperLessApi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8000:8081
    volumes:
      - ./src/PaperLessApi:/app/src
      - /app/src/bin
      - /app/src/obj

  paperlessfrontend:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - paperlessapi
    volumes:
      - ./src/PaperLessFrontend:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/nginx.conf
