version: '3.4'

services:
  paperless-db:
    container_name: paperless-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - paperless-network

  paperless-webapi:
    container_name: paperless-webapi
    image: sims2001/paperless-webapi:master
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - paperless-db
    ports:
      - 8081:8081
    networks:
      - paperless-network

  paperless-frontend:
    container_name: paperless-frontend
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./PaperLess.Frontend:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - paperless-network
    depends_on:
      - paperless-webapi

  paperless-db-admin:
    container_name: paperless-db-admin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: paperless@example.com
      PGADMIN_DEFAULT_PASSWORD: paperless
    depends_on:
      - paperless-db
    networks:
      - paperless-network


networks:
  paperless-network:
    driver: bridge

volumes:
  db-data: