version: '3.4'

services:
  paperless-db:
    container_name: paperless-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - paperless-network

  paperless-storage:
    container_name: paperless-storage
    image: quay.io/minio/minio
    environment:
      MINIO_ACCESS_KEY: paperless
      MINIO_SECRET_KEY: paperless
      MINIO_ROOT_USER: paperless
      MINIO_ROOT_PASSWORD: paperless
      MINIO_DEFAULT_BUCKETS: paperless-bucket
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio-data:/data
    command: ["server", "/data", "--console-address", ":9090"]
    networks:
      - paperless-network

  paperless-webapi:
    container_name: paperless-webapi
    #image: paperless-webapi
    image: sims2001/paperless-webapi:master
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - paperless-db
      - paperless-storage
    ports:
      - 8081:8081
    networks:
      - paperless-network

  paperless-frontend:
    container_name: paperless-frontend
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./PaperLess.Frontend:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - paperless-network
    depends_on:
      - paperless-webapi

  paperless-db-admin:
    container_name: paperless-db-admin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: paperless@example.com
      PGADMIN_DEFAULT_PASSWORD: paperless
    depends_on:
      - paperless-db
    networks:
      - paperless-network


networks:
  paperless-network:
    driver: bridge

volumes:
  db-data:
  minio-data: