version: '3.4'

services:
  paperless-db:
    container_name: paperless-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  paperless-storage:
    container_name: paperless-storage
    image: quay.io/minio/minio
    environment:
      MINIO_ACCESS_KEY: paperless
      MINIO_SECRET_KEY: paperless
      MINIO_ROOT_USER: paperless
      MINIO_ROOT_PASSWORD: paperless
      MINIO_DEFAULT_BUCKETS: paperless-bucket
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio-data:/data
    command: ["server", "/data", "--console-address", ":9090"]

  paperless-queue:
    container_name: paperless-queue
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "9093:15672"
    environment:
      RABBITMQ_DEFAULT_USER: paperless
      RABBITMQ_DEFAULT_PASS: paperless
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  paperless-elastic:
    container_name: paperless-elastic
    image: elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "xpack.security.enrollment.enabled=false"
    ports:
      - 9200:9200
      - 9300:9300

  paperless-webapi:
    container_name: paperless-webapi
    image: sims2001/paperless-webapi:master
    #build: 
    #  context: ./PaperLess.REST
    #  dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - paperless-db
      - paperless-storage
      - paperless-queue
      - paperless-elastic
    ports:
      - 8081:8081

  paperless-frontend:
    container_name: paperless-frontend
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./PaperLess.Frontend:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - paperless-webapi

  paperless-db-admin:
    container_name: paperless-db-admin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: paperless@example.com
      PGADMIN_DEFAULT_PASSWORD: paperless
    depends_on:
      - paperless-db



  paperless-ocr-worker:
    container_name: paperless-ocr-worker
    image: sims2001/paperless-ocr-worker:master
    #build: 
    #  context: .
    #  dockerfile: ./PaperLess.OCR/Dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - paperless-db
      - paperless-queue
      - paperless-storage
      - paperless-webapi
      - paperless-elastic

volumes:
  db-data:
  minio-data:
  rabbitmq-data:
