/*
 * Paperless Rest Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PaperLess.WebApi.Converters;

namespace PaperLess.WebApi.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreateUISettingsRequestSettingsDarkMode 
    {
        /// <summary>
        /// Gets or Sets UseSystem
        /// </summary>
        [Required]
        [DataMember(Name="use_system", EmitDefaultValue=true)]
        public bool UseSystem { get; set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        [Required]
        [DataMember(Name="enabled", EmitDefaultValue=false)]
        public string Enabled { get; set; }

        /// <summary>
        /// Gets or Sets ThumbInverted
        /// </summary>
        [Required]
        [DataMember(Name="thumb_inverted", EmitDefaultValue=false)]
        public string ThumbInverted { get; set; }

    }
}
