name: Build REST API
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -f PaperLess.WebApi/Dockerfile -t paperless-webapi .
        docker tag paperless-webapi ${{ secrets.DOCKERHUB_USERNAME }}/paperless-webapi:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/paperless-webapi:latest