name: Build REST API
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compose Docker
      uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "docker-compose.yml"