name: Build REST API
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compose Docker
      uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "docker-compose.yml"
    - name: Upload image
      uses: ishworkh/docker-image-artifact-upload@v2.0.1
      with:
        image: "paperless-api:latest"